; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dewasa_master]
platform = espressif32
board = denky32
framework = arduino

; Faster upload speed (921600 is usually the optimal speed)
upload_speed = 921600

; Enable compression for faster upload
board_build.flash_mode = qio
board_build.f_flash = 80000000L

; Optional: Add monitor speed to match the Serial.begin() in your code
monitor_speed = 115200
src_filter = +<DeWasaNode_Master.cpp>


; Library dependencies
lib_deps =
    ; WiFi library is included in ESP32 platform by default
    ; esp_now is included in ESP32 platform by default
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson @ ^6.20.0
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.6  ; Required by DHT library
    claws/BH1750 @ ^1.3.0
    ; Wire library is included in Arduino framework by default

[env:get_mac_address]
platform = espressif32
board = denky32
framework = arduino
monitor_speed = 115200
; Faster upload speed (921600 is usually the optimal speed)
upload_speed = 921600

; Enable compression for faster upload
board_build.flash_mode = qio
board_build.f_flash = 80000000L

src_filter = +<GetMacAddress.cpp> -<DeWasaNode_Master.cpp>

[env:peremajaan_node]
platform = espressif32
board = denky32
framework = arduino
; Faster upload speed (921600 is usually the optimal speed)
upload_speed = 921600

; Enable compression for faster upload
board_build.flash_mode = qio
board_build.f_flash = 80000000L
monitor_speed = 115200
src_filter = +<PeremajaanNode.cpp> -<DeWasaNode_Master.cpp> -<GetMacAddress.cpp>
; Library dependencies
lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.6
    claws/BH1750 @ ^1.3.0
